'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Both objects are equal!.
        '''</summary>
        Friend ReadOnly Property BothObjectsEqual() As String
            Get
                Return ResourceManager.GetString("BothObjectsEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection failed!!! Try changing the credentials or the server name..
        '''</summary>
        Friend ReadOnly Property ConnectionFailed() As String
            Get
                Return ResourceManager.GetString("ConnectionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error comparing objects.
        '''</summary>
        Friend ReadOnly Property ErrorComparingObjects() As String
            Get
                Return ResourceManager.GetString("ErrorComparingObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First server name must be specified.
        '''</summary>
        Friend ReadOnly Property FirstServerMustBeSpecified() As String
            Get
                Return ResourceManager.GetString("FirstServerMustBeSpecified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GO\n.
        '''</summary>
        Friend ReadOnly Property Go() As String
            Get
                Return ResourceManager.GetString("Go", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JobServer.
        '''</summary>
        Friend ReadOnly Property JobServer() As String
            Get
                Return ResourceManager.GetString("JobServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Object 1 URN and Object 2 URN need to be set.
        '''</summary>
        Friend ReadOnly Property Object1AndObject2NotSet() As String
            Get
                Return ResourceManager.GetString("Object1AndObject2NotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property {0} can not be found.
        '''</summary>
        Friend ReadOnly Property PropertyNotFound() As String
            Get
                Return ResourceManager.GetString("PropertyNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property {0} is not ICollection.
        '''</summary>
        Friend ReadOnly Property PropertyNotICollection() As String
            Get
                Return ResourceManager.GetString("PropertyNotICollection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Second server name must be specified.
        '''</summary>
        Friend ReadOnly Property SecondServerMustBeSpecified() As String
            Get
                Return ResourceManager.GetString("SecondServerMustBeSpecified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected objects are identical (property wise).
        '''</summary>
        Friend ReadOnly Property SelectedObjectsIdentical() As String
            Get
                Return ResourceManager.GetString("SelectedObjectsIdentical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Object1 Urn by pressing the [Browse] button.
        '''</summary>
        Friend ReadOnly Property SelectObject1Urn() As String
            Get
                Return ResourceManager.GetString("SelectObject1Urn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Object2 Urn by pressing the [Browse] button.
        '''</summary>
        Friend ReadOnly Property SelectObject2Urn() As String
            Get
                Return ResourceManager.GetString("SelectObject2Urn", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
