//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40903.31
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.SqlServer.Properties {
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Appending script: {0} of {1}".
        /// </summary>
        public static string AppendingScript {
            get {
                return ResourceManager.GetString("AppendingScript", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Please choose a table".
        /// </summary>
        public static string ChooseTable {
            get {
                return ResourceManager.GetString("ChooseTable", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Discovering: {0} of {1}".
        /// </summary>
        public static string Discovering {
            get {
                return ResourceManager.GetString("Discovering", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Done".
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "No database selected".
        /// </summary>
        public static string NoDatabaseSelected {
            get {
                return ResourceManager.GetString("NoDatabaseSelected", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Scripting: {0} of {1}".
        /// </summary>
        public static string Scripting {
            get {
                return ResourceManager.GetString("Scripting", _resCulture);
            }
        }
    }
}
