'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SMO Scripter - .
        '''</summary>
        Friend ReadOnly Property AppTitle() As String
            Get
                Return ResourceManager.GetString("AppTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assemblies.
        '''</summary>
        Friend ReadOnly Property Assemblies() As String
            Get
                Return ResourceManager.GetString("Assemblies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Columns.
        '''</summary>
        Friend ReadOnly Property Columns() As String
            Get
                Return ResourceManager.GetString("Columns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Databases.
        '''</summary>
        Friend ReadOnly Property Databases() As String
            Get
                Return ResourceManager.GetString("Databases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Type.
        '''</summary>
        Friend ReadOnly Property DataType() As String
            Get
                Return ResourceManager.GetString("DataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Created.
        '''</summary>
        Friend ReadOnly Property DateCreated() As String
            Get
                Return ResourceManager.GetString("DateCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DummyNode.
        '''</summary>
        Friend ReadOnly Property DummyNode() As String
            Get
                Return ResourceManager.GetString("DummyNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generating script....
        '''</summary>
        Friend ReadOnly Property GeneratingScript() As String
            Get
                Return ResourceManager.GetString("GeneratingScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Object Name.
        '''</summary>
        Friend ReadOnly Property ObjectName() As String
            Get
                Return ResourceManager.GetString("ObjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Name.
        '''</summary>
        Friend ReadOnly Property PropertyName() As String
            Get
                Return ResourceManager.GetString("PropertyName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server.
        '''</summary>
        Friend ReadOnly Property Server() As String
            Get
                Return ResourceManager.GetString("Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Procedures.
        '''</summary>
        Friend ReadOnly Property StoredProcedures() As String
            Get
                Return ResourceManager.GetString("StoredProcedures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tables.
        '''</summary>
        Friend ReadOnly Property Tables() As String
            Get
                Return ResourceManager.GetString("Tables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unrecognized type: .
        '''</summary>
        Friend ReadOnly Property UnrecognizedType() As String
            Get
                Return ResourceManager.GetString("UnrecognizedType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urn.
        '''</summary>
        Friend ReadOnly Property Urn() As String
            Get
                Return ResourceManager.GetString("Urn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USED BY.
        '''</summary>
        Friend ReadOnly Property UsedBy() As String
            Get
                Return ResourceManager.GetString("UsedBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend ReadOnly Property Value() As String
            Get
                Return ResourceManager.GetString("Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Views.
        '''</summary>
        Friend ReadOnly Property Views() As String
            Get
                Return ResourceManager.GetString("Views", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Where Used.
        '''</summary>
        Friend ReadOnly Property WhereUsed() As String
            Get
                Return ResourceManager.GetString("WhereUsed", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
