//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.37
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.Samples.SqlServer.Properties.Resources.get_ResourceManager():System.Res" +
    "ources.ResourceManager")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.Samples.SqlServer.Properties.Resources.get_Culture():System.Globalizati" +
    "on.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="Microsoft.Samples.SqlServer.Properties.Resources.set_Culture(System.Globalization" +
    ".CultureInfo):Void")]

namespace Microsoft.Samples.SqlServer.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad configuration file: Type is null &amp;&amp; Property is null &amp;&amp; Urn is null @ &lt;Ignore&gt; tag no. {0}.
        /// </summary>
        internal static string BadConfigurationFile {
            get {
                return ResourceManager.GetString("BadConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad configuration file: Type is null &amp;&amp; Property is null @ CanBeNullReference no. {0}.
        /// </summary>
        internal static string BadConfigurationFileNullReference {
            get {
                return ResourceManager.GetString("BadConfigurationFileNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing {0} and {1}.
        /// </summary>
        internal static string Comparing {
            get {
                return ResourceManager.GetString("Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} have different numbers of properties: {2} and {3}.
        /// </summary>
        internal static string DifferentNumberProperties {
            get {
                return ResourceManager.GetString("DifferentNumberProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two DBs have different numbers of tables.
        /// </summary>
        internal static string DifferentNumberTables {
            get {
                return ResourceManager.GetString("DifferentNumberTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two DBs have different numbers of views.
        /// </summary>
        internal static string DifferentNumberViews {
            get {
                return ResourceManager.GetString("DifferentNumberViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create the first object: {0}.
        /// </summary>
        internal static string ErrorCreatingFirstObject {
            get {
                return ResourceManager.GetString("ErrorCreatingFirstObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create the first object.
        /// </summary>
        internal static string ErrorCreatingFirstObjectException {
            get {
                return ResourceManager.GetString("ErrorCreatingFirstObjectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create the second object: {0}.
        /// </summary>
        internal static string ErrorCreatingSecondObject {
            get {
                return ResourceManager.GetString("ErrorCreatingSecondObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create the second object.
        /// </summary>
        internal static string ErrorCreatingSecondObjectException {
            get {
                return ResourceManager.GetString("ErrorCreatingSecondObjectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Trying to load configuration file; {0}.
        /// </summary>
        internal static string ErrorLoadingConfiguration {
            get {
                return ResourceManager.GetString("ErrorLoadingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Trying to load configuration file from the same dir as SMOCompare.dll.
        /// </summary>
        internal static string ErrorLoadingConfigurationException {
            get {
                return ResourceManager.GetString("ErrorLoadingConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR in reading data from the second object: {0}.
        ///EXCEPTION: {1}.
        /// </summary>
        internal static string ErrorReadingFirst {
            get {
                return ResourceManager.GetString("ErrorReadingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR in reading data from the first object: {0}.
        ///EXCEPTION: {1}.
        /// </summary>
        internal static string ErrorReadingSecond {
            get {
                return ResourceManager.GetString("ErrorReadingSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception --&gt;&gt;: {0}.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while comparing: {0} with {1}.
        /// </summary>
        internal static string ExceptionWhileComparing {
            get {
                return ResourceManager.GetString("ExceptionWhileComparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The field count for the two objects is different!.
        /// </summary>
        internal static string FieldCountDiffers {
            get {
                return ResourceManager.GetString("FieldCountDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGNORED EXCEPTION: {0}.
        /// </summary>
        internal static string IgnoredException {
            get {
                return ResourceManager.GetString("IgnoredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the objects has more than {0} rows..
        /// </summary>
        internal static string MoreRows {
            get {
                return ResourceManager.GetString("MoreRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL Reference exception, these properties shouldn&apos;t be null: smoObject1[{0}] and smoObject2[{1}] have NULL properties {2} and {3}..
        /// </summary>
        internal static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} couldn&apos;t be created.
        /// </summary>
        internal static string ObjectNotCreated {
            get {
                return ResourceManager.GetString("ObjectNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects to compare have different types, {0} and {1}.
        /// </summary>
        internal static string ObjectsHaveDifferentTypes {
            get {
                return ResourceManager.GetString("ObjectsHaveDifferentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These objects are not databases, not tables, not views!!!.
        /// </summary>
        internal static string ObjectsNotDatabaseEtc {
            get {
                return ResourceManager.GetString("ObjectsNotDatabaseEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaximumLength={0}, Name={1}, NumericPrecision={2}, NumericScale={3}, Schema={4}, SqlDataType={5}, .
        /// </summary>
        internal static string ObjectValue {
            get {
                return ResourceManager.GetString("ObjectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Type has schema and the other doesn&apos;t.
        ///This is a bug in this component;
        ///Please copy the stack trace and file a bug against it..
        /// </summary>
        internal static string OneTypeHasSchema {
            get {
                return ResourceManager.GetString("OneTypeHasSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** PROPERTY NAME NOT SET YET ***.
        /// </summary>
        internal static string PropertyNameNotSet {
            get {
                return ResourceManager.GetString("PropertyNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading property: {0}.
        /// </summary>
        internal static string ReadingProperty {
            get {
                return ResourceManager.GetString("ReadingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server 1 or Server 2 properties can not be null.
        /// </summary>
        internal static string ServerPropertiesCannotBeNull {
            get {
                return ResourceManager.GetString("ServerPropertiesCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types: {0}, {1}.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: {0}, {1}.
        /// </summary>
        internal static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
    }
}
