//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40903.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.SqlServer.Properties {
    
    
    sealed partial class Settings : System.Configuration.ApplicationSettingsBase {
        
        private static Settings m_Value;
        
        private static object m_SyncObject = new object();
        
        [System.Diagnostics.DebuggerNonUserCode()]
        public static Settings Default {
            get {
                if ((Settings.m_Value == null)) {
                    System.Threading.Monitor.Enter(Settings.m_SyncObject);
                    if ((Settings.m_Value == null)) {
                        try {
                            Settings.m_Value = new Settings();
                        }
                        finally {
                            System.Threading.Monitor.Exit(Settings.m_SyncObject);
                        }
                    }
                }
                return Settings.m_Value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.ApplicationScopedSettingAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Profiler\\Templates\\Microsoft SQL S" +
           "erver\\100\\Standard.tdf")]
        public string TraceConfigFile {
            get {
                return ((string)(this["TraceConfigFile"]));
            }
        }
    }
}
