'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.26
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup and Restore Database - .
        '''</summary>
        Friend ReadOnly Property AppTitle() As String
            Get
                Return ResourceManager.GetString("AppTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Backing up the database
        '''.
        '''</summary>
        Friend ReadOnly Property BackingUp() As String
            Get
                Return ResourceManager.GetString("BackingUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Backup complete!
        '''.
        '''</summary>
        Friend ReadOnly Property BackupComplete() As String
            Get
                Return ResourceManager.GetString("BackupComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Backup.
        '''</summary>
        Friend ReadOnly Property BackupSetName() As String
            Get
                Return ResourceManager.GetString("BackupSetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed: {0}.
        '''</summary>
        Friend ReadOnly Property CompletedPercent() As String
            Get
                Return ResourceManager.GetString("CompletedPercent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generated script
        '''.
        '''</summary>
        Friend ReadOnly Property GeneratedScript() As String
            Get
                Return ResourceManager.GetString("GeneratedScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample Backup Media Set # 1.
        '''</summary>
        Friend ReadOnly Property MediaDescription() As String
            Get
                Return ResourceManager.GetString("MediaDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set #1.
        '''</summary>
        Friend ReadOnly Property MediaName() As String
            Get
                Return ResourceManager.GetString("MediaName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..
        '''</summary>
        Friend ReadOnly Property ProgressCharacter() As String
            Get
                Return ResourceManager.GetString("ProgressCharacter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you really want to restore the {0} database?
        '''*** Note: This will overwrite the existing database. ***.
        '''</summary>
        Friend ReadOnly Property ReallyRestore() As String
            Get
                Return ResourceManager.GetString("ReallyRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Restore complete!
        '''.
        '''</summary>
        Friend ReadOnly Property RestoreComplete() As String
            Get
                Return ResourceManager.GetString("RestoreComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring the database
        '''.
        '''</summary>
        Friend ReadOnly Property Restoring() As String
            Get
                Return ResourceManager.GetString("Restoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample Backup of {0}.
        '''</summary>
        Friend ReadOnly Property SampleBackup() As String
            Get
                Return ResourceManager.GetString("SampleBackup", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
