'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bad configuration file: Type is null &amp;&amp; Property is null &amp;&amp; Urn is null @ &lt;Ignore&gt; tag no. {0}.
        '''</summary>
        Friend ReadOnly Property BadConfigurationFile() As String
            Get
                Return ResourceManager.GetString("BadConfigurationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bad configuration file: Type is null &amp;&amp; Property is null @ CanBeNullReference no. {0}.
        '''</summary>
        Friend ReadOnly Property BadConfigurationFileNullReference() As String
            Get
                Return ResourceManager.GetString("BadConfigurationFileNullReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comparing {0} and {1}.
        '''</summary>
        Friend ReadOnly Property Comparing() As String
            Get
                Return ResourceManager.GetString("Comparing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} and {1} have different numbers of properties: {2} and {3}.
        '''</summary>
        Friend ReadOnly Property DifferentNumberProperties() As String
            Get
                Return ResourceManager.GetString("DifferentNumberProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The two DBs have different numbers of tables.
        '''</summary>
        Friend ReadOnly Property DifferentNumberTables() As String
            Get
                Return ResourceManager.GetString("DifferentNumberTables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The two DBs have different numbers of views.
        '''</summary>
        Friend ReadOnly Property DifferentNumberViews() As String
            Get
                Return ResourceManager.GetString("DifferentNumberViews", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error trying to create the first object: {0}.
        '''</summary>
        Friend ReadOnly Property ErrorCreatingFirstObject() As String
            Get
                Return ResourceManager.GetString("ErrorCreatingFirstObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error trying to create the first object.
        '''</summary>
        Friend ReadOnly Property ErrorCreatingFirstObjectException() As String
            Get
                Return ResourceManager.GetString("ErrorCreatingFirstObjectException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error trying to create the second object: {0}.
        '''</summary>
        Friend ReadOnly Property ErrorCreatingSecondObject() As String
            Get
                Return ResourceManager.GetString("ErrorCreatingSecondObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error trying to create the second object.
        '''</summary>
        Friend ReadOnly Property ErrorCreatingSecondObjectException() As String
            Get
                Return ResourceManager.GetString("ErrorCreatingSecondObjectException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR: Trying to load configuration file; {0}.
        '''</summary>
        Friend ReadOnly Property ErrorLoadingConfiguration() As String
            Get
                Return ResourceManager.GetString("ErrorLoadingConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR: Trying to load configuration file from the same dir as SMOCompare.dll.
        '''</summary>
        Friend ReadOnly Property ErrorLoadingConfigurationException() As String
            Get
                Return ResourceManager.GetString("ErrorLoadingConfigurationException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR in reading data from the second object: {0}.
        '''EXCEPTION: {1}.
        '''</summary>
        Friend ReadOnly Property ErrorReadingFirst() As String
            Get
                Return ResourceManager.GetString("ErrorReadingFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR in reading data from the first object: {0}.
        '''EXCEPTION: {1}.
        '''</summary>
        Friend ReadOnly Property ErrorReadingSecond() As String
            Get
                Return ResourceManager.GetString("ErrorReadingSecond", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception --&gt;&gt;: {0}.
        '''</summary>
        Friend ReadOnly Property Exception() As String
            Get
                Return ResourceManager.GetString("Exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception while comparing: {0} with {1}.
        '''</summary>
        Friend ReadOnly Property ExceptionWhileComparing() As String
            Get
                Return ResourceManager.GetString("ExceptionWhileComparing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR: The field count for the two objects is different!.
        '''</summary>
        Friend ReadOnly Property FieldCountDiffers() As String
            Get
                Return ResourceManager.GetString("FieldCountDiffers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IGNORED EXCEPTION: {0}.
        '''</summary>
        Friend ReadOnly Property IgnoredException() As String
            Get
                Return ResourceManager.GetString("IgnoredException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One of the objects has more than {0} rows..
        '''</summary>
        Friend ReadOnly Property MoreRows() As String
            Get
                Return ResourceManager.GetString("MoreRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NULL Reference exception, these properties shouldn&apos;t be null: smoObject1[{0}] and smoObject2[{1}] have NULL properties {2} and {3}..
        '''</summary>
        Friend ReadOnly Property NullReferenceException() As String
            Get
                Return ResourceManager.GetString("NullReferenceException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Object {0} couldn&apos;t be created.
        '''</summary>
        Friend ReadOnly Property ObjectNotCreated() As String
            Get
                Return ResourceManager.GetString("ObjectNotCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Objects to compare have different types, {0} and {1}.
        '''</summary>
        Friend ReadOnly Property ObjectsHaveDifferentTypes() As String
            Get
                Return ResourceManager.GetString("ObjectsHaveDifferentTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to These objects are not databases, not tables, not views!!!.
        '''</summary>
        Friend ReadOnly Property ObjectsNotDatabaseEtc() As String
            Get
                Return ResourceManager.GetString("ObjectsNotDatabaseEtc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MaximumLength={0}, Name={1}, NumericPrecision={2}, NumericScale={3}, Schema={4}, SqlDataType={5}, .
        '''</summary>
        Friend ReadOnly Property ObjectValue() As String
            Get
                Return ResourceManager.GetString("ObjectValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One Type has schema and the other doesn&apos;t.
        '''This is a bug in this component;
        '''Please copy the stack trace and file a bug against it..
        '''</summary>
        Friend ReadOnly Property OneTypeHasSchema() As String
            Get
                Return ResourceManager.GetString("OneTypeHasSchema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *** PROPERTY NAME NOT SET YET ***.
        '''</summary>
        Friend ReadOnly Property PropertyNameNotSet() As String
            Get
                Return ResourceManager.GetString("PropertyNameNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reading property: {0}.
        '''</summary>
        Friend ReadOnly Property ReadingProperty() As String
            Get
                Return ResourceManager.GetString("ReadingProperty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server 1 or Server 2 properties can not be null.
        '''</summary>
        Friend ReadOnly Property ServerPropertiesCannotBeNull() As String
            Get
                Return ResourceManager.GetString("ServerPropertiesCannotBeNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Types: {0}, {1}.
        '''</summary>
        Friend ReadOnly Property Types() As String
            Get
                Return ResourceManager.GetString("Types", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Values: {0}, {1}.
        '''</summary>
        Friend ReadOnly Property Values() As String
            Get
                Return ResourceManager.GetString("Values", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
