//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40903.31
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.SqlServer.Properties {
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Both objects are equal!".
        /// </summary>
        public static string BothObjectsEqual {
            get {
                return ResourceManager.GetString("BothObjectsEqual", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Connection failed!!! Try changing the credentials or the server name.".
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Error comparing objects".
        /// </summary>
        public static string ErrorComparingObjects {
            get {
                return ResourceManager.GetString("ErrorComparingObjects", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "First server name must be specified".
        /// </summary>
        public static string FirstServerMustBeSpecified {
            get {
                return ResourceManager.GetString("FirstServerMustBeSpecified", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Object 1 URN and Object 2 URN need to be set".
        /// </summary>
        public static string Object1AndObject2NotSet {
            get {
                return ResourceManager.GetString("Object1AndObject2NotSet", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Property {0} can not be found".
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Property {0} is not ICollection".
        /// </summary>
        public static string PropertyNotICollection {
            get {
                return ResourceManager.GetString("PropertyNotICollection", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Second server name must be specified".
        /// </summary>
        public static string SecondServerMustBeSpecified {
            get {
                return ResourceManager.GetString("SecondServerMustBeSpecified", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "The selected objects are identical (property wise)".
        /// </summary>
        public static string SelectedObjectsIdentical {
            get {
                return ResourceManager.GetString("SelectedObjectsIdentical", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Select Object1 Urn by pressing the [Browse] button".
        /// </summary>
        public static string SelectObject1Urn {
            get {
                return ResourceManager.GetString("SelectObject1Urn", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Select Object2 Urn by pressing the [Browse] button".
        /// </summary>
        public static string SelectObject2Urn {
            get {
                return ResourceManager.GetString("SelectObject2Urn", _resCulture);
            }
        }
    }
}
