//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both objects are equal!.
        /// </summary>
        internal static string BothObjectsEqual {
            get {
                return ResourceManager.GetString("BothObjectsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed!!! Try changing the credentials or the server name..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comparing objects.
        /// </summary>
        internal static string ErrorComparingObjects {
            get {
                return ResourceManager.GetString("ErrorComparingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First server name must be specified.
        /// </summary>
        internal static string FirstServerMustBeSpecified {
            get {
                return ResourceManager.GetString("FirstServerMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO\n.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobServer.
        /// </summary>
        internal static string JobServer {
            get {
                return ResourceManager.GetString("JobServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object 1 URN and Object 2 URN need to be set.
        /// </summary>
        internal static string Object1AndObject2NotSet {
            get {
                return ResourceManager.GetString("Object1AndObject2NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} can not be found.
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is not ICollection.
        /// </summary>
        internal static string PropertyNotICollection {
            get {
                return ResourceManager.GetString("PropertyNotICollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second server name must be specified.
        /// </summary>
        internal static string SecondServerMustBeSpecified {
            get {
                return ResourceManager.GetString("SecondServerMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected objects are identical (property wise).
        /// </summary>
        internal static string SelectedObjectsIdentical {
            get {
                return ResourceManager.GetString("SelectedObjectsIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Object1 Urn by pressing the [Browse] button.
        /// </summary>
        internal static string SelectObject1Urn {
            get {
                return ResourceManager.GetString("SelectObject1Urn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Object2 Urn by pressing the [Browse] button.
        /// </summary>
        internal static string SelectObject2Urn {
            get {
                return ResourceManager.GetString("SelectObject2Urn", resourceCulture);
            }
        }
    }
}
