//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.36
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in SMOPing argument ({0}).
        /// </summary>
        internal static string ArgumentError {
            get {
                return ResourceManager.GetString("ArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String: {0}.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout: {0}.
        /// </summary>
        internal static string ConnectTimeout {
            get {
                return ResourceManager.GetString("ConnectTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Mode: {0}.
        /// </summary>
        internal static string ExecutionMode {
            get {
                return ResourceManager.GetString("ExecutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMOPing [-S] [-U -P | -E] [-T] [-V] [-v] [-?]
        ///  -S server name
        ///  -U user name
        ///  -P password
        ///  -E integrated security, defaults to true, overrides -U option
        ///  -T connection timeout (seconds)
        ///  -V verbose mode, defaults to false
        ///  -v display SQL Server version
        ///  -? help and usage information
        ///.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Using integrated security ***.
        /// </summary>
        internal static string IntegratedSecurity {
            get {
                return ResourceManager.GetString("IntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pool Size: {0}.
        /// </summary>
        internal static string MaxPoolSize {
            get {
                return ResourceManager.GetString("MaxPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Pool Size: {0}.
        /// </summary>
        internal static string MinPoolSize {
            get {
                return ResourceManager.GetString("MinPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Protocol: {0}.
        /// </summary>
        internal static string NetworkProtocol {
            get {
                return ResourceManager.GetString("NetworkProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketSize: {0}.
        /// </summary>
        internal static string PacketSize {
            get {
                return ResourceManager.GetString("PacketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooled Connection Lifetime: {0}.
        /// </summary>
        internal static string PooledConnectionLifetime {
            get {
                return ResourceManager.GetString("PooledConnectionLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &lt;Enter&gt; to continue.
        /// </summary>
        internal static string PressEnter {
            get {
                return ResourceManager.GetString("PressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Using SQLServer security ***.
        /// </summary>
        internal static string SQLSecurity {
            get {
                return ResourceManager.GetString("SQLSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server login: {0}.
        /// </summary>
        internal static string SqlServerLogin {
            get {
                return ResourceManager.GetString("SqlServerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server name: {0}.
        /// </summary>
        internal static string SqlServerName {
            get {
                return ResourceManager.GetString("SqlServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server version: {0}.{1}.{2}.
        /// </summary>
        internal static string SqlServerVersion {
            get {
                return ResourceManager.GetString("SqlServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Timeout: {0}.
        /// </summary>
        internal static string StatementTimeout {
            get {
                return ResourceManager.GetString("StatementTimeout", resourceCulture);
            }
        }
    }
}
